### PR TITLE
fix: set alternate when using floating windows (#285)

### PR DESCRIPTION
**Pull request by iovis**
This ensures the alternate is set even when using `open_float()`, I copied the code from `restore_alt_buf`, so I'm sure there could be refactor opportunities. Let me know your thoughts!

Fixes: #285

### CODE REVIEW

**Comment by stevearc** [comment]
Everything related to the alternate buffer is very tricky. Please add at least one test to cover this case in https://github.com/stevearc/oil.nvim/blob/master/tests/altbuf_spec.lua. Make sure that it fails without your change applied and passes with it.

**Comment by iovis** [comment]
I completely missed the tests, my bad. I'll give it a go tonight!

**Comment by iovis** [comment]
Done, sorry for missing the tests! I confirmed the new test fails in master but passes on my branch.

**Review by stevearc — CHANGES_REQUESTED** [review]
Thanks for adding the test! I fiddled with it a bit on my end, and I think that a simpler fix is to remove the `keepalt = true` on this line.

https://github.com/stevearc/oil.nvim/blob/7a55ede5e745e31ea8e4cb5483221524922294bf/lua/oil/init.lua#L721

That handles the float win case for me, and doesn't seem to impact any of the other tests.

**Comment by iovis** [comment]
> Thanks for adding the test! I fiddled with it a bit on my end, and I think that a simpler fix is to remove the keepalt = true on this line.

You're right, I can confirm it works on my end and it looks like a much more appropriate fix. I just sent the revised code!

**Comment by stevearc** [comment]
Something strange going on with the test failures in 0.8. I'll investigate when I get a chance

**Comment by iovis** [comment]
I think I found the issue in v0.8, when I removed `keepalt` completely this table:

```lua
-- lua/oil/init.lua:717
local mods = {                  
  vertical = opts.vertical,     
  horizontal = opts.horizontal, 
  split = opts.split,           
}                               
```

Could result in an empty table, which apparently neovim v0.8 doesn't like:

```
Error executing vim.schedule lua callback: ~/code/vim/oil.nvim/lua/oil/init.lua:745: 'mods' must be a Dictionary
stack traceback:
        [C]: in function 'cmd'
        ~/code/vim/oil.nvim/lua/oil/init.lua:745: in function 'callback'
        ~/code/vim/oil.nvim/lua/oil/adapters/files.lua:260: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Changing it from removing it completely to `keepalt = false` resolves the issue and the tests still pass (which I cleaned up a bit).

**Comment by stevearc** [comment]
Great, thanks for the fix!

**Comment by tjex** [comment]
Thank you so much for this everyone!!!!

**Pull request merged**
