### PR TITLE
refactor: move loading message delay to config

### PR DESCRIPTION
**Pull request by kevintraver**
This allows `loading_message_delay` to be overridden

### CODE REVIEW

**Comment by stevearc** [comment]
In general I want to avoid exposing additional options in the config unless they are necessary. The list of options is already quite large, and it makes it hard for users to find what they're looking for. Could you describe the issue you are trying to solve with this, and why this is necessary?

**Comment by kevintraver** [comment]
I sometimes see the loading indicator flash, and would like to set it to a higher value.

Maybe this can be something thats not in config by default, but still in the docs and is can be added manually.

**Comment by stevearc** [comment]
What is a value that would cause it to not flicker for you? 100ms was pulled from nowhere in particular, and I'm _probably_ fine with any number below 500ms. I wouldn't even blink at bumping to 200ms.

**Comment by kevintraver** [comment]
Yeah, it does not flicker at 200ms.

**Comment by stevearc** [comment]
Delay updated to 200ms

**Pull request closed without merging**
